name = "echosenseix"
compatibility_date = "2024-04-03"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "storage_db"
database_id = "9d996182-1b5e-4845-977d-8ad1b7f1f562"
